Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,9 +16,10 @@ jobs:
       - name: Run Trivy vulnerability scanner
         id: trivy_scan
         uses: aquasecurity/trivy-action@master
+        continue-on-error: true  # Permitir que el flujo de trabajo continúe ejecutándose incluso si Trivy falla
         with:
           image-ref: 'docker.io/library/debian:9'
-          exit-code: '0'  # Cambia el exit-code a '0' para que el escaneo continúe incluso si se encuentran vulnerabilidades
+          exit-code: '1'  # Cambia el exit-code a '1' para que falle si se encuentran vulnerabilidades
           ignore-unfixed: true
           vuln-type: 'os,library'
           severity: 'CRITICAL,HIGH'
@@ -32,10 +33,12 @@ jobs:
         with:
           sarif_file: 'trivy-results.sarif'
 
-      - name: Check vulnerabilities found
+      - name: Check vulnerabilities and fail if needed
         if: ${{ always() }}
-        run: echo "Vulnerabilities found: ${{ steps.trivy_scan.outputs.trivy_results_json }}"
-
-      - name: Fail workflow if critical vulnerabilities found
-        if: ${{ always() && steps.trivy_scan.outputs.trivy_results_json }}
-        run: exit 1  # Fuerza el fallo de la ejecución si se encuentran vulnerabilidades críticas
+        run: |
+          if grep -q '"vulnerabilities":\[\]' trivy-results.sarif; then
+            echo "No vulnerabilities found."
+          else
+            echo "Vulnerabilities found. Failing workflow."
+            exit 1
+          fi
