Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,17 +20,24 @@ jobs:
           image-ref: 'docker.io/library/neo4j:5.18.0-community-ubi9'
           format: 'sarif'
           output: 'trivy-results.sarif'
-          exit-code: '0' # Set exit code to 1 to make the step fail if vulnerabilities are found
+          exit-code: '0'
 
       - name: Upload Trivy scan results to GitHub Security tab
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: 'trivy-results.sarif'
 
-      # Fail the pipeline if Trivy scan step fails (indicating vulnerabilities were found)
-      - name: Check Trivy scan status
-        if: ${{ failure() }}
-        run: echo "Trivy scan failed due to vulnerabilities found, failing the pipeline." && exit 1
+      # Store the exit code in an output variable
+      - name: Store Trivy scan exit code
+        if: always() # This step always runs to store the exit code
+        id: store_exit_code
+        run: echo "::set-output name=trivy_exit_code::${{ steps.trivy_scan.outputs.exit_code }}"
+
+# Final step to fail the pipeline if Trivy scan had exit code 0
+- name: Fail pipeline if Trivy scan had exit code 0
+  if: ${{ steps.store_exit_code.outputs.trivy_exit_code == '0' }}
+  run: exit 1
+
 
     
     
